### PR TITLE
u3d/unity_versions: fix missing latest versions

### LINKED ISSUE #330: No Beta versions visible with u3d available
### Issue Checklist

- [x ] I'm using the latest u3d version
- [ x] I ran `u3d --help`
- [ x] I read the [README](https://github.com/DragonBox/u3d/blob/master/README.md)
- [ x] I made sure that a similar [issue](https://github.com/DragonBox/u3d/issues) doesn't exit

### Issue Description

u3d available or u3d available --no-central does not list beta versions. If this is intended, how can I use u3d to install the latest beta version? (which at the moment is Unity 2018.3.0b8)

### PR DESCRIPTION
**Pull request by niezbop**
### Pull Request Checklist

- [x] My pull request has been rebased on master
- [x] I ran `bundle exec rspec` to make sure that my PR didn't break any test
- [x] I ran `bundle exec rubocop` to make sure that my PR is inline with our code style
- [x] I have read the [code of conduct](https://github.com/DragonBox/u3d/blob/master/CODE_OF_CONDUCT.md)

### Pull Request Description

Unity has recently updated their listing of the latest releases for betas notably.
This restore the functionnality by fetching the latest information.

Fixes #330

### CODE REVIEW

File: spec/u3d/unity_versions_spec.rb [hunk 1]
```diff
@@ -44,18 +44,46 @@ def fake_linux_ini_data(size, url)
...
     describe '.list_available' do
       it 'retrieves windows versions' do
-        expect(U3d::Utils).to receive(:get_ssl) { "" } # lts
-        expect(U3d::Utils).to receive(:get_ssl) { windows_archive }
-        expect(U3d::Utils).to receive(:get_ssl).at_least(2).times { "" }
-        expect(U3d::UnityVersions.list_available(os: :win).count).to eql 3
+        expect(U3d::UnityVersions).to receive(:fetch_version_paged).at_least(3).times { {} }
+        expect(U3d::UnityVersions).to receive(:fetch_version).at_least(3).times { {} }
+        expect(U3d::UnityVersions).to receive(:fetch_from_json).at_least(:once) { {} }
+        expect(U3d::UnityVersions.list_available(os: :win).count).to eql 0
```
Comment (lacostej) [inline spec/u3d/unity_versions_spec.rb]: why 0 available?

File: spec/u3d/unity_versions_spec.rb [hunk 2]
```diff
@@ -44,18 +44,46 @@ def fake_linux_ini_data(size, url)
...
       end
       it 'retrieves mac versions' do
-        expect(U3d::Utils).to receive(:get_ssl) { "" } # lts
-        expect(U3d::Utils).to receive(:get_ssl) { macosx_archive }
-        expect(U3d::Utils).to receive(:get_ssl).at_least(2).times { "" }
-        expect(U3d::UnityVersions.list_available(os: :mac).count).to eql 3
+        expect(U3d::UnityVersions).to receive(:fetch_version_paged).at_least(6).times { {} }
+        expect(U3d::UnityVersions).to receive(:fetch_version).at_least(6).times { {} }
+        expect(U3d::UnityVersions).to receive(:fetch_from_json).at_least(:once) { {} }
+        expect(U3d::UnityVersions.list_available(os: :mac).count).to eql 0
```
Comment (lacostej) [inline spec/u3d/unity_versions_spec.rb]: same

File: spec/u3d/unity_versions_spec.rb [hunk 3]
```diff
@@ -44,18 +44,46 @@ def fake_linux_ini_data(size, url)
...
+      end
+
+      it 'reads versions for mac' do
+        expect(U3d::Utils).to receive(:get_ssl) { macosx_archive }
+        expect(U3d::UnityVersions.fetch_version("foo", U3d::UnityVersions::MAC_DOWNLOAD).count).to eql 3
+      end
+    end
+
+    # TODO: test U3d::UnityVersions.fetch_version_paged
+    xdescribe '.fetch_version_paged' do
```
Comment (lacostej) [inline spec/u3d/unity_versions_spec.rb]: needed?

File: spec/u3d/unity_versions_spec.rb (hunk 1 above)
Comment (lacostej) [reply spec/u3d/unity_versions_spec.rb]: maybe we want to rename the description (i.e. to "it retrieves from various sources") or something more related to what we now test here.

File: lib/u3d/unity_versions.rb [hunk 4]
```diff
@@ -114,6 +114,8 @@ module UnityVersions
     UNITY_BETAS = 'https://unity3d.com/unity/beta/archive'.freeze
```
Comment (lacostej) [inline lib/u3d/unity_versions.rb]: if this is broken fully, then either we document this isn't used (and change the content) or remove the field and bump the minor version of u3d.
