### PR TITLE
u3d/install: do not reinstall already installed packages

### LINKED ISSUE #198: Incorrect package check downloads and reinstalls it
If I run on Windows, for example:

u3d install 2017.3.0f3 -p Mac
u3d install 2017.3.0f3 -p Linux
u3d install 2017.3.0f3 -p iOS

Always installs it but for other packages like Android or WebGL it says that it's already installed so it skips it like it should do for Mac, Linux or iOS.

I want in Jenkins to always run this command on my builds before running Unity so I can be sure that it's already installed. But if it's going to install it every time I run that command despite of being already installed it's not worth it because it takes some minutes to install something that it was already installed.

Also, it would be nice for download packages to:
- Allow to select the folder where we want to download it.
- Allow to delete the download packages after a correct installation.

In our case we use it in CI servers that we don't want to fill the hard drive with Unity installation files.

Thanks for you hard work, it's a really nice tool.

### PR DESCRIPTION
**Pull request by niezbop**
Fixes #198 

This solve the issues of non-matching package name between installed and available by:

- Mapping the names of the installed package and the available package
- Detecting some folders on the local install for "special package" (Documentation, Standard Assets...)

### CODE REVIEW

**Comment by niezbop** [comment]
This is still __[WIP]__ because:

- _Example_ package is still not detected as it is not installed in the install but in the public home (ie `C:\Users\Public\Documents\Unity Projects\Standard Assets Example Project` on Windows), and I'm not sure we want to track this, especially given the fact that it probably shouldn't be installed in the first place on a CI environment.
- We lack local folder detection for Mac, as I have limited access to this OS for now.

File: lib/u3d/installation.rb [hunk 1]
```diff
@@ -179,9 +179,18 @@ def path
 
     def packages
       path = "#{root_path}/Editor/Data/"
-      PlaybackEngineUtils.list_module_configs(path).map do |mpath|
-        PlaybackEngineUtils.module_name(mpath)
+      pack = []
+      PlaybackEngineUtils.list_module_configs(path).each do |mpath|
+        pack << PlaybackEngineUtils.module_name(mpath)
       end
+      pack << 'Documentation' if specific_dir?("#{root_path}/Editor/Data/Documentation/", check_empty: true)
```
Comment (lacostej) [inline lib/u3d/installation.rb]: we could have a method under each PlatformInstallation called

```
def module_files_pattern(module_name)
  return "#{root_path}/Editor/Data/Documentation/*" if module_name == "Documentation"
  return ....
end
```

or something similar

and then do a 
```
['Documentation', 'StandardAssets', 'MonoDevelop'].each do |module_name|
  patern = module_files_pattern(module_name)
  pack << module_name if Dir.glob(pattern).count > 0
end
```

better idea?

File: lib/u3d/commands.rb [hunk 2]
```diff
@@ -328,8 +328,11 @@ def enforce_setup_coherence(packages, options, unity, definition)
             options[:installation_path] ||= unity.root_path if definition.os == :win
           end
           if unity.packages
-            unity.packages.each do |pack|
-              UI.important "Ignoring #{pack} module, it is already installed" if packages.delete(pack)
+            installed_packages = unity.packages
+            packages.each do |pack|
+              if installed_packages.include?(pack) || installed_packages.any? { |installed| !package_aliases[pack].nil? && package_aliases[pack].include?(installed) }
```
Comment (lacostej) [inline lib/u3d/commands.rb]: feel free to move this whole logic into a method "package_installed?" or similar.

File: lib/u3d/commands.rb [hunk 3]
```diff
@@ -328,8 +328,11 @@ def enforce_setup_coherence(packages, options, unity, definition)
...
+                UI.important "Ignoring #{pack} module, it is already installed" if packages.delete(pack)
```
Comment (lacostej) [inline lib/u3d/commands.rb]: Does the if need to go away?

```
packages.delete(pack)
UI.important "Ignoring #{pack} module, it is already installed"
```

File: lib/u3d/installation.rb (hunk 1 above)
Comment (lacostej) [reply lib/u3d/installation.rb]: I installed 2017.3.0f3 on the first slave with all sub-modules, in case you need to find the paths.

**Comment by niezbop** [comment]
Implemented modifications and the Mac part. `Example` question is still not solved, should we try to detect it as well?

File: lib/u3d/commands.rb [hunk 4]
```diff
@@ -342,6 +341,45 @@ def enforce_setup_coherence(packages, options, unity, definition)
...
+
+        installed_packages = unity.packages
+        packages.each do |pack|
+          result << pack if package_installed?(pack, installed_packages)
+        end
+
+        result
+      end
+
+      def package_installed?(package, installed_packages)
```
Comment (lacostej) [inline lib/u3d/commands.rb]: would it be better to move this to unity? I don't think command should have too much logic anyway.

E.g. if `unity.package_installed?` existed, it would be less code here.

File: lib/u3d/installation.rb [hunk 5]
```diff
@@ -90,8 +90,26 @@ def path
...
+    def module_name_pattern(module_name)
+      case module_name
+      when 'Documentation'
+        return "#{root_path}/Documentation/"
+      when 'StandardAssets'
+        return "#{root_path}/Standard Assets/"
+      when 'MonoDevelop'
+        return "#{root_path}/MonoDevelop.app/"
+      else
+        return ''
```
Comment (lacostej) [inline lib/u3d/installation.rb]: fail here instead of silent return

File: lib/u3d/installation.rb [hunk 6]
```diff
@@ -90,8 +123,26 @@ def path
...
+    def module_name_pattern(module_name)
+      case module_name
+      when 'Documentation'
+        return "#{root_path}/Documentation/"
+      when 'StandardAssets'
+        return "#{root_path}/Standard Assets/"
+      when 'MonoDevelop'
+        return "#{root_path}/MonoDevelop.app/"
+      else
+        UI.user_error! "No pattern is known for #{module_name} on Mac"
```
Comment (lacostej) [inline lib/u3d/installation.rb]: maybe  `crash!` instead?

File: spec/support/installations.rb [hunk 7]
```diff
@@ -95,5 +95,6 @@ def fake_installation(version, packages: [])
   allow(unity).to receive(:version) { version }
   allow(unity).to receive(:root_path) { 'foo' }
   allow(unity).to receive(:packages) { packages }
+  unity.stub(:package_installed?) { |arg| packages.include?(arg) }
```
Comment (lacostej) [inline spec/support/installations.rb]: Maybe keep using `allow` instead of the somewhat deprecated `stub`?

https://relishapp.com/rspec/rspec-mocks/v/2-14/docs/method-stubs/stub-with-substitute-implementation

File: lib/u3d/installation.rb [hunk 8]
```diff
@@ -90,8 +123,26 @@ def path
     end
 
     def packages
-      PlaybackEngineUtils.list_module_configs(root_path).map do |mpath|
-        PlaybackEngineUtils.module_name(mpath)
+      pack = []
+      PlaybackEngineUtils.list_module_configs(root_path).each do |mpath|
+        pack << PlaybackEngineUtils.module_name(mpath)
+      end
+      %w[Documentation StandardAssets MonoDevelop].each do |module_name|
```
Comment (lacostej) [inline lib/u3d/installation.rb]: Let's move that to a module or Installation class constant. Maybe something like SPECIAL_PACKAGES? Better name idea?

File: lib/u3d/installation.rb [hunk 9]
```diff
@@ -44,6 +44,39 @@ def self.create(root_path: nil, path: nil)
...
+        'Vuforia-AR' => ['UnityExtensions']
+      }
+    end
+
+    def packages
+      false
+    end
+
+    def package_installed?(package)
+      return false unless packages
```
Comment (lacostej) [inline lib/u3d/installation.rb]: we can replace the two lines with

```
return true if (packages || []).include?(package)
```

and maybe change the default `packages` implementation to return a `[]` instead of false?

File: lib/u3d/installation.rb [hunk 10]
```diff
@@ -44,6 +44,39 @@ def self.create(root_path: nil, path: nil)
...
+
+      return true if packages.include?(package)
+
+      aliases = Installation.package_aliases[package]
+      return false if aliases[package].nil?
```
Comment (lacostej) [inline lib/u3d/installation.rb]: I don't think `aliases[package]` can get nil. You meant empty right?

In which case, we may just skip the line entirely as it is covered by the next one?

Comment (niezbop) [reply lib/u3d/installation.rb]: I believe it can when the package is not known ie `aliases['NewPackage'] = nil`. It makes it so that we don't crash when some package is not known, which would make u3d unusable for versions with unknown packages. So this lane is mandatory imo.

File: lib/u3d/installation.rb [hunk 11]
```diff
@@ -44,6 +46,37 @@ def self.create(root_path: nil, path: nil)
         WindowsInstallation.new(root_path: root_path, path: path)
       end
     end
+
+    def self.package_aliases
```
Comment (lacostej) [inline lib/u3d/installation.rb]: This could be cached as well into a `PACKAGE_ALIASES` and documented.

**Comment by lacostej** [comment]
We should add some tests to the `Installation` classes changes at least. I am sure things will break when we have different Unity versions.
