### PR TITLE
u3d/installer: support custom install paths through U3D_EXTRA_PATHS

### LINKED ISSUE #370: u3d list command does not work in non-standard path
I have previously installed a version of the editor with this command:

`u3d install 2019.2.11f1 -p Android --installation_path "E:\Unity2019.2.11f1"`

I tried to list the installed versions of Unity and it tells me that there is none and I see in the code that it is because it only searches the default paths set by u3d.

https://github.com/DragonBox/u3d/blob/c4a01f8c8b6ded2877471b43360eeb4bc617a72e/lib/u3d/installer.rb#L365

I understand that in the "list" command should have an option to pass one or several different paths where to search.

Something like this:

`u3d list --paths "E:/Unity" "C:/Program Files/"`

### LINKED ISSUE #371: installation_path parameter problems
This command works correctly:

`u3d install 2019.2.11f1 --installation_path "E:\Unity2019.2.11f1"`

If I run the same command again it reinstalls it instead of saying it is already installed.

Also if I want to install a module in the same path later it is impossible for me.

`u3d install 2019.2.11f1 -p Android --installation_path "E:\Unity2019.2.11f1"`

I get the following error:

`Please install Unity before any of its packages`

I don't know if it's related to this other bug:

#370

### PR DESCRIPTION
**Pull request by niezbop**
### Pull Request Checklist

- [x] My pull request has been rebased on master
- [x] I ran `bundle exec rspec` to make sure that my PR didn't break any test
- [x] I ran `bundle exec rubocop` to make sure that my PR is inline with our code style
- [x] I have read the [code of conduct](https://github.com/DragonBox/u3d/blob/master/CODE_OF_CONDUCT.md)

### Pull Request Description

`u3d install` supports custom installation paths, but does not list them correctly in the rest of the application.
This means that `u3d run`, package installs and such commands will not detect properly the version installed in a custom path.

This fixes this behaviour by adding an environment variable `U3D_EXTRA_PATHS` which is a list of additional paths to look for installed Unity versions.

Fixes #370 
Fixes #371

### CODE REVIEW

File: lib/u3d/installer.rb [hunk 1]
```diff
@@ -86,6 +86,21 @@ def installed_sorted_by_versions
...
     end
+
+    protected
+
+    def extra_installation_paths
+      return [] if ENV['U3D_EXTRA_PATHS'].nil?
+      ENV['U3D_EXTRA_PATHS'].strip.split(';')
+    end
+
+    def find_installations_with_path(default_path, *postfix)
```
Comment (lacostej) [inline lib/u3d/installer.rb]: Not super fond of the use of variable arguments with a first argument here. No better idea yet.

File: lib/u3d/installer.rb [hunk 2]
```diff
@@ -169,9 +184,12 @@ def uninstall(unity: nil)
     private
 
     def list_installed_paths
-      find = File.join(DEFAULT_MAC_INSTALL, 'Applications', 'Unity*', 'Unity.app')
-      paths = Dir[find]
-      paths = paths.map { |u| Pathname.new(u).parent.to_s }
+      paths = find_installations_with_path(
+        DEFAULT_MAC_INSTALL,
```
Comment (lacostej) [inline lib/u3d/installer.rb]: Side note: I made some work on #287 that was changing this. In particular I was modifying the `DEFAULT_MAC_INSTALL` on Mac to be `/Applications`. To make it more similar to the way the other platforms are managed.

Comment (lacostej) [reply lib/u3d/installer.rb]: We can deal with this later. It was just a reminder.

Comment (niezbop) [reply lib/u3d/installer.rb]: Yep, I saw your work because I got a bit startled at the Applications being repeated all the way through, but I'm not sure that this would work. Unity installation path takes a volume as an argument. I tried doing `u3d install 2019.2.1.f1 --installation_path ~` and it wouldn't work.

File: lib/u3d/installer.rb [hunk 3]
```diff
@@ -86,6 +86,21 @@ def installed_sorted_by_versions
       return [] if list.empty?
       list.sort { |a, b| UnityVersionComparator.new(a.version) <=> UnityVersionComparator.new(b.version) }
     end
+
+    protected
+
+    def extra_installation_paths
+      return [] if ENV['U3D_EXTRA_PATHS'].nil?
+      ENV['U3D_EXTRA_PATHS'].strip.split(';')
```
[the remark this answers is not in the document]
Comment (niezbop) [reply lib/u3d/installer.rb]: Good idea! I actually looked for the differences in PATH specifications between Windows and Unix, but didn't want to build something just for this. Thanks for that

File: lib/u3d/installer.rb (hunk 1 above)
Comment (niezbop) [reply lib/u3d/installer.rb]: Maybe a named argument for the first one?

**Comment by niezbop** [comment]
Understood. I did think about having some sort of `~/.u3d/installation_paths` config file, which could be expanded when using `--installation_path`, but I find that a bit less robust, since it introduces some "magic" that would get broken if the installation was to be moved.

My rationale is that with the introduction of the Unity Hub and its CLI, `u3d` may be more and more a CI tool than a Unity developer tool. In this perspective, I think an environment variable works best since it is more easily accessible through CI platforms and easier to automate as well.

And from a user perspective, one could only have to specify the env in the .bashrc or something. Maybe we could a comment about this when installing Unity at an usual location. Something like:
```
You specified --installation_path LOCATION. You will need to add LOCATION to U3D_EXTRA_PATHS to make sure that the other commands can find your installation.
```

**Comment by bdovaz** [comment]
I'll explain our case which is very simple.

Until now we had a 256GB SSD disk for the operating system and the different versions of Unity. As you can imagine, it is very short because we work with many projects in parallel in different versions of Unity and different platforms. This makes the disk fill very fast.

Recently we have installed in two Jenkins nodes two 1TB SSD disks and that's when I found the problem of not being able to automate what I had until now in non-standard directories.

For our case, which is CI, it is good that they are environment variables because they are very easy to configure.

File: lib/u3d/installer.rb (hunk 1 above)
Comment (lacostej) [reply lib/u3d/installer.rb]: Maybe. And maybe we should call it default_root_path?
